### DISCUSSION TITLE
Just panel

### DISCUSSION THREAD

**Discussion by GH0st3rs** [modoboa/modoboa#3469] [Help]
Hi I would like to set up just panel without all other included services.
Your manual installation guide incorrect and doesn't useful. Your installer will install and configure all-in-one without ability to host most services outside.

Why you can not just wrap your code to the separate docker container? Something like:
```
services:
  modoboa-panel:
    image: modoboa/modoboa-panel:latest
    environment:
      - DB_TYPE=psql
      - DB_NAME=db1
      - DB_password=pwd1
      - DB_USER=user1
      - DB_HOST=host1
      - AMAVIS_HOST=host2:port
      - ETC...
    volumes:
      - all needed configuration files here
```
With `initialize` command to be able to initialize empty remote database
```
docker-compose ... exec manage.py initialize
```

It will allow users to run it everywhere and use different configurations on the different OS
Why it's so hard? you just use python+django there is no magic here
